config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    collection do
      # /restaurants/top
      # get 'top', to: 'restaurants#top', as: :top_restaurants
      # after here, go to controller and code top method
      # get :top # generates '/restaurants/top'
      # get '/balances', to: 'balances#controller'
      get :top
    end

    member do
      # /restaurants/:id/chef
      get :chef
    end

    # NESTING:
    # /restaurants/:restaurant_id/reviews
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

# COLLECTIONS:
# collections is a method in rails that allows us to
# to create new routes inside the context we are in:
# inside of resources restaurants (inside resources)

# NESTING: ONLY NEST COLLECTION ACTIONS, NEVER MEMBER ACTIONS!
# we are going to nest the route of our reviews inside our restaurants
# because it is related to the restaurant and everytime i create a review
# i need to grab a restaurant id. This id comes from the url.

# DESTROY:
# rails routes | grep reviews
# it is outside of the nesting because it doesnt need an id
# of the restaurant. we only nest when we need an id in the url.
# i dont need a restaurant anymore, all I need is the id of my review

# ONLY NEST COLLECTION ACTIONS!
# https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # we don't want to have reviews that belong to a deleted restaurant;
  # now i can call any restaurant instance.reviews(@restaurant.reviews);
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find, only: [:show, :edit, :update, :destroy, :chef]

  def index
    @restaurants = Restaurant.all
  end

  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  def chef
    # find the restaurant first (before_action)
    @chef_name = @restaurant.chef_name
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    # no view (comes from new view)
    @restaurant = Restaurant.new(restaurant_params) 
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    # no view (comes from edit view)
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    # no view (comes from show view)
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  # before show, edit, update and destroy run this code!
  def find
    @restaurant = Restaurant.find(params[:id])
  end
end

# ActiveModel::ForbiddenAttributesError
# 1:10mins CRUD class

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, except: [:destroy]
  def new
    @review = Review.new
  end

  def create
    # this instance of review is created with validation errors
    @review = Review.new(review_params)
    # we need to associate our review to a restaurant(restaurant_id)
    # because so far this is what we have: <Review id: nil, rating: 5, content: "amazing", restaurant_id: nil, created_at: nil, updated_at: nil>
    # in the console: new_review.restaurant = eatery
    @review.restaurant = @restaurant
    # if not empty due to validations it will save. then:
    # raise
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      # we will stay in the create action but will display the template of the new page
      # the only difference is that i am not using the "new" instance of @review, i am
      # using the instance of review that failed to save.
      # we can look at this instance on rails c using new_review.errors.messages
      # simple form handles that
      # render renders some html, it renders a page
      # if THE SAVE fails it will render a new page, and what is this new page?
      # essentially my form.
      # this instance of @review has validations and will show errors
      # renders the "new" route, a new form
      render :new
    end
  end

  def destroy
    # if we had nested we would have needed: @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
    @review.destroy
    # restaurant show page
    redirect_to restaurant_path(@review.restaurant) # which is the restaurant that belongs to my review
  end

  private

  def find_restaurant
    # in our routes for reviews it is :restaurant_id
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

# to generate the route we need in our simple form
# we are gonna  add the restaurant instead of @review.
# so we will pass an array with BOTH [@restaurant,@review]
# to generate the route that we want

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating, as: :radio_buttons, collection: [['Good', '1', { class: "one-star" }], ['Very Good', '2', { class: "two-stars" }], ["Excellent", 3, { class:"three-stars" } ]] %>
  <%= f.submit %>
<% end %>

app/views/restaurants/chef.html.erb
<h1><%= @restaurant.name %>'s chef is <%= @chef_name %>.</h1>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<br>
<%= link_to 'Create a new Restaurant', new_restaurant_path, class: "btn btn-secondary" %>
<br>
<br>
<% @restaurants.each do |restaurant| %>
  <h5><%= link_to restaurant.name, restaurant_path(restaurant)%> <%= '⭐' * restaurant.rating %></h5>
  <p><%= restaurant.address%></p>
<% end %>

app/views/restaurants/new.html.erb
<%= render 'form' %>
<hr>
<%= link_to 'Back to restaurants', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %> <%= '⭐' * @restaurant.rating%></h1>
  <p><%= @restaurant.address%></p>

  <%# iterates over the reviews %>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %></li>
      <%= link_to 'delete', review_path(review), method: :delete, data: { confirm: "Are you sure?" } %>
      <hr>
    <% end %>
  </ul>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>  |
<%= link_to 'Delete Restaurant', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?'}%>  |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>
<hr>
<%= link_to 'Back to restaurants', restaurants_path %>

app/views/restaurants/top.html.erb
<h1>My top Restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <p> <%= restaurant.name %> <%= '⭐' * restaurant.rating %></p>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.association :restaurant, required: false %>
  <%= f.input :content, required: false %>
  <!-- adds bootstrap button  -->
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<!-- we need: -->
<!-- <form action="/restaurants/101/reviews/new" method="post"></form> -->
<%# simple_form_for [@review] %>
<!-- this will generate a form with action 'reviews' only! -->
<!-- which will return error: undefined method `reviews_path'  -->
<!-- that would give us a '/reviews' and we don't have that in our routes -->
<!-- in our routes we have: -->
<!-- /restaurants/:restaurant_id/reviews
/restaurants/:restaurant_id/reviews/new -->
<!-- we need action '/restaurants/:id/reviews/new' -->

<!-- we dont have any references added to our restaurant model. We need
to get the id!! -->

<!-- WHAT TO DO: -->
<!-- - find restaurant in the reviews controller; -->
<!-- GO BACK TO TEACHER.MD -->

<%# 
Helper	HTTP request
simple_form_for(@review)	POST reviews_path (does not exist)
simple_form_for([@restaurant, @review])	POST restaurant_reviews_path %>